apiVersion: v1
kind: Service
metadata:
  name: testproj-service
  namespace: testproj-namespace
spec:
  selector:
    app: testproj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
