apiVersion: v1
kind: Service
metadata:
  name: testproj-service
  namespace: testproj
  labels:
    app: testproj
spec:
  selector:
    app: testproj
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
